[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "queso-cluster"
version = "0.0.0"
authors = [
	{name = "Sarah Riley", email="sarah.riley1@montana.edu"}
]

description = "Quantifying the Evolution of Spectra with Optimization"
readme = "README.md"
requires-python=">=3.9"

license = {file = "LICENSE"}

dependencies = [
	"numpy",
	"dkist",
	"scipy",
	"numba",
	"astropy",
	"numba_progress",
	"dask",
	"pyyaml",
	"tol-colors",
]

[project.urls]
Homepage = "https://queso.sriley.dev"
