name = "Quantifying the Evolution of Spectra with Optimization"
version = "0.0.1"
authors = [
	{name = "Sarah Riley", email="sarah.riley1@montana.edu"}
]

description = ""
readme = "README.md"
requires-python=">=3.9"

license = ""
license-files=["LICENSE"]

[project.urls]
Homepage = "queso.sriley.dev"
