[project]
name = "QuESO"
version = "0.0.1"
authors = [
  { name="Sarah Riley", email="sarah.riley1@montana.edu" },
]
description = "Quantifying the Evolution of Spectra with Optimization"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = ""
Issues = ""